### ISSUE TITLE
Graphdash Compatibility

### ISSUE THREAD

**Issue by geotekberlin** [Virsacer/icingaweb2-module-rrdtool#1]
Hi Virsacer, I would like to make my [Icinga Graphdash module](https://exchange.icinga.com/geotek/GraphDash%20Module%20for%20Icinga%202) compatible with your rrdtool module. Graphdash uses an extended default.php file but when it is used with rrdtool the graphs are cut off.

Tested on Icingaweb 2.9.5 with Firefox 95.0.2

Any idea why your rrdtool does not like my default.php ?

[default.zip](https://github.com/Virsacer/icingaweb2-module-rrdtool/files/7792790/default.zip)

**Comment by Virsacer** [comment]
Hi,
apparently pnp4nagios did start counting at 0 for `$this->DS`, while starting at 1 for other variables...
I did not notice this because all templates I have, use a `foreach` instead of accessing the elements directly.

**Comment by geotekberlin** [comment]
Hi Virsacer, Thank you for your quick fix, that solved the general display clipping problem. Most Graphs now show correctly but some check types show empty results for example check_ping, check_disk.exe or the Interface Powershell Check:

![Screenshot_1](https://user-images.githubusercontent.com/15341250/147761901-58a66d17-8eaa-4eb0-94be-473d14c7dd1e.png)

![Screenshot_2](https://user-images.githubusercontent.com/15341250/147761906-f0f9d41b-c74e-4bb7-9e36-dc5119e38694.png)

icingaweb2.log shows messages like so:
2021-12-30T12:32:02+01:00 - ERROR - ErrorException in /usr/share/icingaweb2/modules/rrdtool/library/Rrdtool/apply_template.php:40 with message: require(/usr/share/icingaweb2/modules/rrdtool/library/vendor/pnp4nagios/templates/default.php): failed to open stream: Datei oder Verzeichnis nicht gefunden
#0 /usr/share/icingaweb2/modules/rrdtool/library/Rrdtool/apply_template.php(40): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}()
#1 /usr/share/icingaweb2/modules/rrdtool/library/Rrdtool/apply_template.php(40): require()
#2 /usr/share/icingaweb2/modules/rrdtool/application/controllers/GraphController.php(30): require(String)
#3 /usr/share/php/Icinga/Web/Controller/ActionController.php(165): Icinga\Module\rrdtool\Controllers\GraphController->init()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#6 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#7 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#9 {main}

The original pnp module shows all graphs correctly.

Is there anything else I can give you to help spot the Problem?

**Comment by Virsacer** [comment]
Hi,
I also noticed the missing thumbnails at one of my checks.
Can you check if my last commit fixed that for you as well?

Your logmessage is from the previous version and complains that the default-template is missing!?
You can now put your custom default-template in `/usr/share/icingaweb2/modules/rrdtool/templates/`

Can you provide the rrd+xml file from your second screenshot?
Your template works fine for my checks...

**Comment by geotekberlin** [comment]
Hi,
unfortunately your latest build did not solve the issue. no errors in incingaweb2 log. I have enclosed rrd sample files for diagnosis.

[disk-used-win.zip](https://github.com/Virsacer/icingaweb2-module-rrdtool/files/7794416/disk-used-win.zip)

**Comment by Virsacer** [comment]
Unescaped backslashes in labels are bad...

Can you check again?

**Comment by geotekberlin** [comment]
I agree but I am afraid we can't do anything about that if the original icinga checks behave this way. 

With the new build the check_disk.exe graphs are OK now, but the ping graphs are still missing on all hosts and the interface-ps graphs on some hosts. So there must be something else going wrong. Here are the rrd files:

[rrd.zip](https://github.com/Virsacer/icingaweb2-module-rrdtool/files/7795905/rrd.zip)

**Comment by Virsacer** [comment]
Sure :D

With current master they also work fine in my environment:

![image](https://user-images.githubusercontent.com/8797510/147829053-8bbb8679-cda3-4398-bc58-b88afcdb4dea.png)

![image](https://user-images.githubusercontent.com/8797510/147829059-55dec334-e678-4525-9d7a-e47de788516b.png)

I assume you are using the latest RRDtool binary?
Currently I have no other idea...

**Comment by geotekberlin** [comment]
I am using rrdtool 1.7.2-3+b7 from the debian 11 repo which should be quite current.

By the way, the graphs itself are showing correctly, **only the preview graphs are missing for all hostalive4 checks**. 

While looking at possible browser issues I found another bug: In Chrome the date picker fields aren't populated, they look like this:
![Screenshot_1](https://user-images.githubusercontent.com/15341250/147833108-3e549645-224c-48f5-a90c-9a7dd54b237e.png)
with error messsages like so:
![Screenshot_2](https://user-images.githubusercontent.com/15341250/147833119-9278595f-0980-4f14-90a0-f52ed7d7892a.png)
In firefox the datepicker fields are OK. I don't know whether this is related or not but maybe it could point into the right direction?

**Comment by Virsacer** [comment]
Yes 1.7.2 is the latest, so that should not be the problem.

So it still looks like in the first set of your screenshots, exept that "Datasource: rta" now shows a graph?
Did you update all files to master?

The datepicker was unrelated, but thanks for the hint :-)

**Comment by geotekberlin** [comment]
I just re-checked with the current build, same problem. the preview graphs are still missing for all hostalive4 checks and some interface-powershell checks are missing while the graphs itself are OK. 

On the failing interface-ps checks I noticed that there are 10 graphs while you are only showing 7 graphs, 3 are empty like so:
![Screenshot_1](https://user-images.githubusercontent.com/15341250/147857642-6156b637-60ff-4838-8654-4d138029694d.png)

Also the datasource names are erroneously truncated.

Here are sample rrd files of a failing interface-ps check, maybe this helps to reproduce the problem.

[interface-ps.zip](https://github.com/Virsacer/icingaweb2-module-rrdtool/files/7798067/interface-ps.zip)

**Comment by Virsacer** [comment]
Ok, when the first full graph is not working, that would explain the missing thumbnails.
But I still see no reason, why the 3 graphs are missing - I get all 10...
I even tested with the Debian binary (I'm on Ubuntu)

What happens when you right-click a failed image and select "Open Image in New Tab"?

The names are truncated, because you call `CleanupName()` on the name which truncates to 16 characters before you assign it to `$ds_name`.

What version of PHP are you using?
Can you add

    if (is_string($params)) file_put_contents("/tmp/rrdtool.txt", print_r(array($opt, $def), TRUE));
to the end of your template and share the content of `/tmp/rrdtool.txt` after reloading the page from your last screenshot?

**Comment by geotekberlin** [comment]
Showing the failed image in a new tab shows just a tiny image of size 1 x 13 pixels:
![Screenshot_2](https://user-images.githubusercontent.com/15341250/147875860-19b9b9ea-4430-46a7-aad4-4a9e6edab6a7.png)
This is the html source of the portion of interest. The first fieldset is the failing image, the second fieldset is a working image:
![Screenshot_3](https://user-images.githubusercontent.com/15341250/147875904-d9f2cb6d-fa00-42a2-8ab6-56e4309f63f0.png)

I am using PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) from Debian 11 repo
This is the output when rendering the last screenshot:
[rrdtool.txt](https://github.com/Virsacer/icingaweb2-module-rrdtool/files/7799053/rrdtool.txt)
All 10 array entries are there even though images 1, 2 and 5 are missing. Strange...
.

**Comment by geotekberlin** [comment]
I think I found the cause of the problem, it has to do with unit normalization. 

In my [default.php for pnp4nagios](https://geotek.de/cms/archiv/icinga-nagios-plugins) I am normalizing all values to the base unit, for example from ms to s in order to avoid weird values such as 40mms or 40ukWh. Your rta graphs of hostalive4 are failing as soon as I set the normal X axis size to a fraction of 1 second. This is needed in order to see normal round trip delays in the range of 1 to 50 ms in more detail. This works fine with pnp4nagios but breaks your rrdtool graph. 

Could you please check if your module has problems dealing with fractional or floating values?

**Comment by Virsacer** [comment]
Oh, I thought I wrote an answer here...

Version 1.0.5 should fix that.
I noticed that in your rrdtool.txt there were commas where there should have been dots.
After some digging I found that PHP 7.x was respecting the locale for some functions so I added a conversion.

Are the graphs still not working?

**Comment by geotekberlin** [comment]
No, still not working with current master.

**Comment by Virsacer** [comment]
I installed a testenvironment where I was able to reproduce this.
Conversions happen in multiple places, so I changed the locale and that did fix it.

**Comment by geotekberlin** [comment]
Version 1.0.6 did indeed fix the graph problem. Thanks a lot!!

**Comment by Virsacer** [comment]
@geotekberlin
Hi, I found an issue with your default-template:

    A non-numeric value encountered
    
    #0 /usr/share/icingaweb2/modules/rrdtool/templates/default.php(472): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)

It expects a number, but https://nagios-plugins.org/doc/guidelines.html#AEN200 states, that "U" is a valid value.
