### ISSUE TITLE
Rrdtool using deprecated functions (PhP 8.2)

### ISSUE THREAD

**Issue by neutronc** [Virsacer/icingaweb2-module-rrdtool#10]
Good days,
the following message we get after upgrading the underlying platform (OS and middleware).
Deprecated
: Creation of dynamic property Icinga\Module\Rrdtool\Controllers\GraphController::$DS is deprecated in
/usr/share/icingaweb2/modules/rrdtool/library/Rrdtool/apply_template.php
on line
6

Deprecated
: Creation of dynamic property Icinga\Module\Rrdtool\Controllers\GraphController::$MACRO is deprecated in
/usr/share/icingaweb2/modules/rrdtool/library/Rrdtool/apply_template.php
on line
25

OS: Debian 12
php: 8.2

Leading to empty graphics on display.

Kind regards

**Comment by Virsacer** [comment]
Hi, I have to look into that...

**Comment by neutronc** [comment]
Thank you

**Comment by Virsacer** [comment]
Youre welcome ;-)
