### ISSUE TITLE
Inconsistent Behaviour of rrdtool ?

### ISSUE THREAD

**Issue by neutronc** [Virsacer/icingaweb2-module-rrdtool#11]
Hi,

i have a number of switches in two enviroments, Production and QS.

While implementing new checks in the QS enviroment i enabled the "Checks with multiple rrds" feature.

Now i have one switch out of 7 or so, where rrdtool is splitting the rrds per interface ? For the other switches running the same checks theres still only one rrd file.
![image](https://github.com/Virsacer/icingaweb2-module-rrdtool/assets/6752457/142a04b2-fbbd-4ad6-81b2-8c4d24f550ae)
This switch is showing only one rrd...

![image](https://github.com/Virsacer/icingaweb2-module-rrdtool/assets/6752457/cb8dd66c-3cc9-467e-98a7-8456f770fe5f)

and thats the behaviour i would have expected from the first one too.

Now wheres the mistake ? :)
What information do you need ? (Ip adresses and system names withheld due to restrictions.
Regards,
Martin

**Comment by Virsacer** [comment]
Hi,

the "Checks with multiple RRDs" setting has only effect on creation of databases.
For existing databases the storage-type is kept to prevent loss of data.

You can convert existing databases with `icingacli rrdtool split Host/Service.xml`

I think I should update the readme...

Best regards
