### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by geotekberlin** [Virsacer/icingaweb2-module-rrdtool#2]
There is a translation issue in the overview graphs. "Year" and "Week" are not translated to German while all others are translated corectly:

![grafik](https://user-images.githubusercontent.com/15341250/152548048-bda8e4ef-c0ca-479a-93f6-1be352a858ae.png)

I have verified in https://translate.icinga.com/ that these untranslated words are already translated in Icinga and Incingaweb2. Are your using your own (incomplete) translations or what is the reason for the failing translations?

My environment:

Icinga r2.13.2-1 on Debian 11
Icinga Web 2 2.9.5
icinga/icinga-php-library 	0.7.0
icinga/icinga-php-thirdparty 	0.10.0
businessprocess 	2.3.1
cube 	1.1.0
director 	1.9.0 master
doc 	2.9.5
graphdash 	1.0.1
idoreports 	0.9.0
incubator 	0.11.0
monitoring 	2.9.5
pdfexport 	0.9.0
rrdtool 	1.0.6
vspheredb 	1.2.1

**Comment by Virsacer** [comment]
Actually I did not provide any translation yet.
Since the thumbnails are embedded in a page of the monitoring-module apparenty its translation is beeing used/tried.

I did some research on how translation works and created a german translation.
