### ISSUE TITLE
Please make template path configurable

### ISSUE THREAD

**Issue by geotekberlin** [Virsacer/icingaweb2-module-rrdtool#3]
Hello Virsacer,

my pnp4nagios templates are at `/usr/local/pnp4nagios/share/templates` and they must stay there because they are used by other means as well. Putting symlinks to my own template location has worked previously, but this is not very elegant, as each update of rrdtool would break things again.

Would it be possible to make this path configurable in rrdtool so that it survives module updates. 

By the way, in the upcoming version of my [GraphDash Module for Icinga](https://geotek.de/cms/archiv/icinga-nagios-plugins) I am about to add a hard coded link to your rrdtool detail graph like so:
`https://<icinga_server>/icingaweb2/rrdtool/graph?host=<hostname>&service=<servicename>&range=<year|month|week|day|hours>`
and this works great. Is this URL likely to stay unchanged in the future?

**Comment by Virsacer** [comment]
Hi,

out of curiosity: What besides pnp (which this module intends to replace) uses pnp-templates?
But sure, I can make the path configurable.

I cant test GraphDash since I dont use the Director. But I think its unlikely that I have to change the URLs.
BTW: The range-parameter supports even more values - see `icingacli rrdtool graph --help`

**Comment by geotekberlin** [comment]
My GrahpDash module uses pnp directly for example as it should work with or without your rrdtool alike. With your rrdtool, however, there is the added benefit of accessing your nice detail view when clicking on one GraphDash Images.

**Comment by geotekberlin** [comment]
Hello @Virsacer, that works great. Thanks a lot and have a nice day!

**Comment by geotekberlin** [comment]
Sorry to bother you again, but I just found a small bug in your template path logic. 

When a custom template path is configured and a certain template is not found in the custom location but is present in your template location, then your template is taken instead of the default template in the configured template path.

**Comment by Virsacer** [comment]
Yes, there is the fallback to the original pnp4nagios templates.

I'll have a look later
