### ISSUE TITLE
rrdtool generating incomplete graphics

### ISSUE THREAD

**Issue by MarBrumm** [Virsacer/icingaweb2-module-rrdtool#5]
While the Stats Graph displaying the module runtime statistics is perfectly fine, the result graphics for the actual checks running on the plattform show besides the threshholds no actual data. (NAN for the actual datapart).

Paths have been verified permissions on /var/lib/icinga2/rrdtool have been adjusted to nagios.nagios.

Cronjob processing the data is running under root privilege. 
![image](https://user-images.githubusercontent.com/116077067/199258069-72a42c9a-900a-4c6f-9b1f-b984d2e7b569.png)

The RRD files can be found in the director, the XML contains statements indicating that data are available but the graphs are empty..
![image](https://user-images.githubusercontent.com/116077067/199258439-83d2812c-c9c7-475f-bd1b-2a06d8b6c755.png)
![image](https://user-images.githubusercontent.com/116077067/199258556-c6c123d2-81dc-4b22-ac41-c3fa95d7c39f.png)

![image](https://user-images.githubusercontent.com/116077067/199261780-18bf0d38-7950-42e9-ae38-a9ae057be08d.png)

Any help or information would be appreciated. If you need more information please dont hesitate to ask.

**Comment by Virsacer** [comment]
Hi,
does the log in RRD/XML-path or `icingacli rrdtool check` indicate any errors?
Are all graphs affected or only specific ones like from check_interfaces?
Are numeric values in the XMLs `<ACT>` section?
NaN might be an issue with locale (dot versus comma)...

BTW: You don't have to configure the paths if you are using the defaults anyway.
pnp4nagios ist the fallback if there is no match in templates and relative paths can be used.

**Comment by MarBrumm** [comment]
Hi, the log does not indicate any recent errors.
On One system i was able to create at least some graphics for about 20 minutes after i deleted all files in the rrdtool subdirectories.. resuming in the following graphics but then it stopped again ?
![image](https://user-images.githubusercontent.com/116077067/199553438-1b262e67-6518-4a80-a4fc-64d87bfd30fd.png)


Any chance to get some more information from logs ?

Fyi the system has above 2300 systems in checks with up to 50 interfaces each... Might the size be an action ?

Regards

**Comment by Virsacer** [comment]
The timestamps in the log are the ones from PerfdataWriter - so "recent" is relative...
Are there piling up files in the PerfdataWriter directory?
What is the runtime of rrdtool?
And what about `icingacli rrdtool check`?

Currently just invalid, skipped and errors in data are gettin logged. Perhaps I can extend that...

With that amount of checks lots of rrd-files have to be written - i/o might become a bottleneck.

**Comment by Virsacer** [comment]
I just realized that you don't have `Checks with multiple RRDs` set - when the datasources change, RRDs wont be able to update

**Comment by MarBrumm** [comment]
> The timestamps in the log are the ones from PerfdataWriter - so "recent" is relative... Are there piling up files in the PerfdataWriter directory? What is the runtime of rrdtool? And what about `icingacli rrdtool check`?
> 
> Currently just invalid, skipped and errors in data are gettin logged. Perhaps I can extend that...
> 
> With that amount of checks lots of rrd-files have to be written - i/o might become a bottleneck.

Problem was and is the limitation of runtime in the Processcommand routine .. (and a mistake by myself to not call the rrdtool process ever minute but only every 10 minutes. ) 
Now the process has to play catchup wih all the historical data...

**Comment by Virsacer** [comment]
The limit is in place to prevent running into the next cronjob execution.

But it is catching up now?

**Comment by MarBrumm** [comment]
yes running well
