### ISSUE TITLE
Possible Support of ICINGA HA funtions ?

### ISSUE THREAD

**Issue by neutronc** [Virsacer/icingaweb2-module-rrdtool#7]
Good morning,
i am wondering how to solve the following scenario using rrdtool:

2 Master systems runing and writing perfdata with the enable_ha option.
So the spool directory should be mounted via nfs for the second master.
And the rrdtool directory needs also to be visible via nfs to the second master..
But now if both masters have the rrdtool running they will constantly interfere with each other.

Any idea or plans to somehow link the rrdtool into the HA-Mechanismn of icinga2 ?

Kind regards

**Comment by Virsacer** [comment]
Hi, 
I just have single nodes and forgot about HA...

From a quick reading of https://icinga.com/docs/icinga-2/latest/doc/14-features/#perfdata-files-in-cluster-ha-zones I got that perfdada should be written to a third server on which the processing takes place...

But you have mounted the directory of node1 on node2?
So when node1 is offline, node2 has no access to the existing perfdata, but starts to write its own?
Maybe I misunderstood, but this does not seem desirable.

I guess I would have both nodes write perfadata locally (with enable_ha only 1 writes, right?) and sync it to a third server, process it there and have the rrd databases synced to the actual server(s) of icingaweb.
That way any server can be offline without dataloss - in case of the processing server, the graphs will just not be updated until it is back up.
