### ISSUE TITLE
Permission problems with NFS mounted directories

### ISSUE THREAD

**Issue by neutronc** [Virsacer/icingaweb2-module-rrdtool#8]
Since we are monitoring a large number of interfaces, we offloaded the processing of the performance data to another system, where we run the rrdtool cron job after syncing the performance data with rsync to the machine.

Since i really wanted to avoid the io-load on the Check running systems, i exported the rrdtool directory from the processing machine towards our Icingaweb2 systems. Initially this worked well and the graphs got displayed.
Now however i get the indication that the permission for rrdtool is not sufficient on the mounted(via nfs) directories.

The permissions on the filesystem shown locally however are displayed as read & writeable by world.
What permissions does icingaweb2-rrdtool expect ?

Kind regards

**Comment by Virsacer** [comment]
Hi,
the module does not expect anything special:

For displaying the graphs, PHP (the user running it) just needs to be able to read the rrd and xml files.
For updating the graphs, the user running the cli command obviously needs to be able to write them.

Keep in mind that the user also needs the permission to access parent directories and network shares to be able to reach the directory containing the files.
You can verify this by logging in as the user (might need to be enabled temporarily) and trying to navigate to the directory.
